// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawIi24W2yUBDkQZGZz_6EXkXnPZKxjfU',
    appId: '1:119031935681:web:e765a0819d81556fb99a40',
    messagingSenderId: '119031935681',
    projectId: 'cash-flow-a27ec',
    authDomain: 'cash-flow-a27ec.firebaseapp.com',
    storageBucket: 'cash-flow-a27ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHBEe8hUQ_eBPXtCiq5P3K3sgy8uFWbyQ',
    appId: '1:119031935681:android:ceb8abbc4c9f399eb99a40',
    messagingSenderId: '119031935681',
    projectId: 'cash-flow-a27ec',
    storageBucket: 'cash-flow-a27ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW6Z9URh8aMvW4QQMll7k58w-BognDGtY',
    appId: '1:119031935681:ios:0173a121c6b82a45b99a40',
    messagingSenderId: '119031935681',
    projectId: 'cash-flow-a27ec',
    storageBucket: 'cash-flow-a27ec.appspot.com',
    iosClientId: '119031935681-u0qqtbree2mvdhmg8rufhpmj9go63i18.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCashFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW6Z9URh8aMvW4QQMll7k58w-BognDGtY',
    appId: '1:119031935681:ios:0173a121c6b82a45b99a40',
    messagingSenderId: '119031935681',
    projectId: 'cash-flow-a27ec',
    storageBucket: 'cash-flow-a27ec.appspot.com',
    iosClientId: '119031935681-u0qqtbree2mvdhmg8rufhpmj9go63i18.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCashFlow',
  );
}
